server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /symbols {
        proxy_pass http://backend:3030;
    }
    location /prices {
        proxy_pass http://backend:3030;
    }
    location /portfolio {
        proxy_pass http://backend:3030;
    }
    location /orders {
        proxy_pass http://backend:3030;
    }
}
